# Generated by Django 4.2 on 2025-11-23 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='size_ml_g',
            field=models.CharField(help_text='e.g., 450ml, 261g', max_length=50, verbose_name='Size (ml/g/oz)'),
        ),
    ]
