# Generated by Django 4.2 on 2025-12-06 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='security_answer',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='account',
            name='security_question',
            field=models.CharField(choices=[('pet', 'What was the name of your first pet?'), ('mother', "What is your mother's maiden name?"), ('city', 'In what city were you born?'), ('school', 'What was the name of your first school?')], default='pet', max_length=50),
        ),
    ]
