# Generated by Django 4.2 on 2025-11-23 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('Delivery', 'Delivery (Courier)'), ('Pickup', 'Pickup (Store Location)')], default='Delivery', max_length=20),
        ),
    ]
