# Generated by Django 4.2 on 2025-11-24 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_rename_is_ordered_orderproduct_ordered_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='estate',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
