# Generated by Django 4.2 on 2025-11-29 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_mpesatransaction'),
        ('orders', '0004_alter_order_city_alter_order_estate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='product_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.productvariant'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
